login: &login
  adapter: mysql2
  database: <%= ENV["DATABASE_NAME"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>


development:
  <<: *login

test:
  <<: *login

production:
  <<: *login
